SELECT	EFname,ELname,Zooid
FROM	EMPLOYEE
WHERE	EXISTS(
		SELECT	*
		FROM	ANIMAL_KIND, ANIMALS_AND_ITS_KIND, LOOK_AFTER
		WHERE	 ANIMALS_AND_ITS_KIND.Aid = LOOK_AFTER.Aid AND Empid = EMPLOYEE.Eid AND ANIMAL_KIND.AName = 'Giraffe' 
		);
